### ISSUE TITLE
CLI Documentation could be clearer on specific details

### ISSUE THREAD

**Issue by achiurizo** [autonomys/subspace-docs#127]
- [x] I'd mention WiFi in networking specifically, it is known to get much less stable in typical consumer routers under load
- [ ] macOS executables say "Intel" and "Apple M1", while it is not necessary M1 as there is M2 already; either call it "Apple Silicon" or "x86-64" and "aarch64"
- [ ] similarly for Ubuntu, we have "Ubuntu Executable" and "Ubuntu Arch Executable" (which I understand what you meant, but doesn't make sense generally), I think it should also just be "x86-64" and "aarch64" and it'll be consistent with macOS

**Comment by jfrank-summit** [comment]
@ozgunozerk is this still applicable?

**Comment by postmeback** [comment]
2nd & 3rd point has been taken care of. But, I am still figuring out the 1st point. Can you guide me on this?

**Comment by ImmaZoni** [comment]
Thanks for the contributions @postmeback 🙏 

In regards to the 1st point, this is admittedly a moving target still. For context on our farmer we utilize a Decentralized Storage Network. Being a P2P network this has the potential to send large amounts of requests through the router causing performance degradation on some routers. (See this issue here: https://github.com/subspace/subspace/issues/1227)

As you can see this issue has been closed, but due to the nature of P2P networks we still need to continue testing. For now it might be best to just explain this context and clarify the general warning for network incendivity. 

We might include something mentioning older/less performant routers may have issues aswell. 

Thanks again for your contributions, happy to assist in any way possible

**Comment by postmeback** [comment]
@ImmaZoni , thanks for the reply. 

Requesting the maintainers to update this issue accordingly.

**Comment by vexr** [comment]
It is stated that `Operating a node and farmer can be data-intensive. It is advisable to have a stable and unlimited internet connection.` If this addresses the WiFi issue, it seems that everything else mentioned has been covered and this issue can be closed.
